version: '3'

services:
  app:
    image: flexberrygogatekeepersample/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=https://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;

  app-postgres-db:
    image: flexberrygogatekeepersample/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
      
  keycloak:
    image: flexberrygogatekeepersample/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - KEYCLOAK:/opt/keycloak/data/

volumes:
  DB:
  KEYCLOAK:
